<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/PML/Day_29_18_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# from google.colab import drive
# drive.mount('/content/drive')


import numpy as np
import pandas as pd

import os
os.chdir('/content/drive/MyDrive/CDAC/')

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

from numpy import random
from collections import Counter

from numpy.linalg import inv
from numpy.linalg import eig

import matplotlib
from matplotlib import pyplot as plt

import seaborn as sns

import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from scipy.stats import chisquare
from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import roc_auc_score

#========================================================================

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.discrete.discrete_model import MNLogit

import sklearn
from sklearn.model_selection import train_test_split



import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

# from category_encoders import BinaryEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier


from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.metrics import mean_squared_error
from math import sqrt


import tensorflow

from tensorflow.keras.models import Sequential # helps with the forward and backward propagation
from tensorflow.keras.layers import Dense # this is for the hidden, input and output layers
from tensorflow.keras.layers import ReLU   # activation function
from tensorflow.keras.layers import Dropout   # switching off the neurons

from sklearn.naive_bayes import GaussianNB

In [5]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name= 'diabetes')

In [63]:
df.columns

Index(['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age', 'Outcome', 'DietType'],
      dtype='object')

In [64]:
df = df[['Glucose', 'BloodPressure', 'Age', 'DietType', 'Outcome']]
df.head(2)

   Glucose  BloodPressure  Age  DietType  Outcome
0      148             72   50         1        1
1       85             66   31         2        0

In [65]:
x = df.drop('Outcome', axis=1)
x.head(2)

   Glucose  BloodPressure  Age  DietType
0      148             72   50         1
1       85             66   31         2

In [66]:
y = df.Outcome
y.head(2)

0    1
1    0
Name: Outcome, dtype: int64

In [67]:
diet_dummy = pd.get_dummies(x.DietType , drop_first = True, prefix='DT').astype(int)
diet_dummy.head() ## what happen over here that pd_get Dummies work

   DT_2  DT_3
0     0     0
1     1     0
2     0     0
3     0     0
4     0     0

In [68]:
x.drop('DietType' , axis=1 , inplace= True)
print(x.head())

x = pd.concat([x,diet_dummy], axis=1)
print(x.head())

   Glucose  BloodPressure  Age
0      148             72   50
1       85             66   31
2      183             64   32
3       89             66   21
4      137             40   33
   Glucose  BloodPressure  Age  DT_2  DT_3
0      148             72   50     0     0
1       85             66   31     1     0
2      183             64   32     0     0
3       89             66   21     0     0
4      137             40   33     0     0

In [69]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2 , random_state=20)
x_train.head(), x_test.head(), y_train.head(), y_test.head()

(     Glucose  BloodPressure  Age  DT_2  DT_3
 446      100             72   28     1     0
 260      191             68   34     1     0
 570       78             70   39     1     0
 590      111             84   45     0     0
 30       109             75   60     1     0,
      Glucose  BloodPressure  Age  DT_2  DT_3
 143      108             66   42     1     0
 14       166             72   51     1     0
 504       96             78   40     1     0
 557      110             76   58     0     1
 736      126             86   21     1     0,
 446    0
 260    0
 570    0
 590    1
 30     0
 Name: Outcome, dtype: int64,
 143    1
 14     1
 504    0
 557    0
 736    0
 Name: Outcome, dtype: int64)

In [70]:
from sklearn.svm import SVC
svc = SVC()
svc

SVC()

In [71]:

params = {'C':[2,4,6,8,10],
	  'kernel':['rbf','linear','poly'],
	  'degree':[1,2,3,4]}

svc_cv = GridSearchCV(estimator=svc, param_grid=params, cv=3,scoring='accuracy')
print(svc_cv)

svc_cv.fit(x_train,y_train)
print(svc_cv)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [2, 4, 6, 8, 10], 'degree': [1, 2, 3, 4],
                         'kernel': ['rbf', 'linear', 'poly']},
             scoring='accuracy')
GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [2, 4, 6, 8, 10], 'degree': [1, 2, 3, 4],
                         'kernel': ['rbf', 'linear', 'poly']},
             scoring='accuracy')

In [72]:
svc_cv.best_params_

{'C': 2, 'degree': 1, 'kernel': 'linear'}

In [73]:
svc = SVC(C=2, degree=1, kernel='linear')

svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)
print(y_pred)

print(confusion_matrix(y_test,y_pred))

SVC(C=2, degree=1, kernel='linear')
[0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0
 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0
 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0
 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 0 0]
[[99  2]
 [17 36]]

# 🔰Support vector Regession🔰

In [10]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name = 'SalesData')

#df = df[['Glucose', 'BloodPressure','Age','DietType','Outcome']]

x = df.drop('Sales', axis=1)
y = df.Sales


region_dummy = pd.get_dummies(x.Region, drop_first=True, prefix='DT').astype(int)
x.drop('Region', axis=1, inplace=True)
x = pd.concat([x,region_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

from sklearn.svm import SVR
svr = SVR()


params = {'C':[2,4,6,8,10],
	  'kernel':['rbf','linear','poly'],
	  'degree':[1,2,3,4],
      'epsilon':[0.01,0.1,0.5,1,5,10]}

svr_cv = GridSearchCV(estimator=svr,param_grid=params,cv=3,scoring='accuracy')
svr_cv.fit(x_train,y_train)




svr_cv.best_params_

# svr = SVR(C=, degree=, kernel= , epsilon=)
# svr.fit(x_train,y_train)
# #y_pred = svr.predict(x_test)
# #rmse = (sum((y_pred-y_test)**2)/len(y_pred))**0.5

# y_pred = dvr.fit(x_train)
# SSE = sum((y_pred-y_train)**2)
# SST = sum((y_train-np.mean(y_train))**2)
# SSR = SST - SSE
# R2 = SSR/SST

KeyboardInterrupt:

In [11]:

svr = SVR(C=, degree=, kernel= , epsilon=)
svr.fit(x_train,y_train)
#y_pred = svr.predict(x_test)
#rmse = (sum((y_pred-y_test)**2)/len(y_pred))**0.5

y_pred = dvr.fit(x_train)
SSE = sum((y_pred-y_train)**2)
SST = sum((y_train-np.mean(y_train))**2)
SSR = SST - SSE
R2 = SSR/SST

SyntaxError: expected argument value expression (812101003.py, line 1)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'diabetes')
df = df[['Glucose', 'BloodPressure','Age','DietType','Outcome']]
x = df.drop('Outcome', axis=1)
y = df.Outcome

diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='DT').astype(int)
x.drop('DietType', axis=1, inplace=True)
x = pd.concat([x,diet_dummy], axis=1)


x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)
mod1 = KNeighborsClassifier(n_neighbors=2)
mod1.fit(x_train,y_train)
y_pred1 = mod1.predict(x_train)
confusion_matrix(y_train,y_pred1)

y_pred2 = mod1.predict(x_test)
confusion_matrix(y_test,y_pred2)

array([[89, 12],
       [33, 20]])

In [9]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name = 'SalesData')

#df = df[['Glucose', 'BloodPressure','Age','DietType','Outcome']]

x = df.drop('Sales', axis=1)
y = df.Sales


region_dummy = pd.get_dummies(x.Region, drop_first=True, prefix='DT').astype(int)
x.drop('Region', axis=1, inplace=True)
x = pd.concat([x,region_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=7)
knn_reg.fit(x_train, y_train)

y_pred = knn_reg.predict(x_train)