<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/PML/Day_21_09_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

import os
os.chdir('/content/drive/MyDrive/CDAC/')

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

from numpy import random
from collections import Counter

from numpy.linalg import inv
from numpy.linalg import eig

import matplotlib
from matplotlib import pyplot as plt

import seaborn as sns

import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from scipy.stats import chisquare
from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f
from sklearn.metrics import mean_squared_error

from sklearn.metrics import roc_auc_score

#========================================================================

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.discrete.discrete_model import MNLogit

import sklearn
from sklearn.model_selection import train_test_split



import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

# from category_encoders import BinaryEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [8]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'diabetes')

df =df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop('Outcome', axis=1)
y = df.Outcome

diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='Diet').astype(int)
x = x.drop('DietType', axis=1)
x = pd.concat([x, diet_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

x_train = sm.add_constant(x_train, prepend=False)
mod3 = sm.Logit(y_train, x_train).fit()
print(mod3.summary())

Optimization terminated successfully.
         Current function value: 0.333614
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      608
Method:                           MLE   Df Model:                            5
Date:                Thu, 18 Jun 2026   Pseudo R-squ.:                  0.4848
Time:                        10:26:06   Log-Likelihood:                -204.84
converged:                       True   LL-Null:                       -397.59
Covariance Type:            nonrobust   LLR p-value:                 3.933e-81
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Glucose           0.0368      0.005      7.867      0.000       0.028       0.046
BloodPressure     0.0058      0.007      0.850      0.395      -0.008       0.019
Age               0.0317      0.011      2.908      0.004       0.010       0.053
Diet_2           -3.9276      0.323    -12.142      0.000      -4.562      -3.294
Diet_3           -2.7806      0.344     -8.076      0.000      -3.455      -2.106
const            -4.3877      0.730     -6.012      0.000      -5.818      -2.957
=================================================================================

## Accuracy is misleading due to misbalanced data to solve this problem we introduced:

$$
\text{Precision} = \frac{TP}{TP + FP}
$$

---

### Recall => True Positive Rate or Sensitivity

$$
\text{Recall} = \frac{TP}{TP + FN}
$$

---

### Recall => False Positive Rate

$$
\text{Recall} = \frac{FP}{TN + FP}
$$

---

### Recall => True Negative Rate (FPR)
### Specificity = 1 - FPR
$$
\text{Recall} = \frac{TN}{FP + TN}
$$

---

- True Positive Rate and the True Nagative Rate will always have a tread-off.
- When the threshold is Low we have more of True Positive but also more number of False Positive.
- When the threshold is high we have more of False Negative but also more number of True Negative.

# 🔰AUC-ROC Curve🔰
(Area under curve - reciever operating characteristic)

## AUC = Is the Probability that two distinct classes will be correctly distinguished

$$
\begin{array}{|c|c|c|}
\hline
\textbf{Case} & \textbf{True Class} & \textbf{Pred Probability} \\
\hline
P1 & 1 & 0.93 \\
P2 & 0 & 0.83 \\
P3 & 0 & 0.31 \\
P4 & 1 & 0.73 \\
P5 & 1 & 0.25 \\
P6 & 0 & 0.37 \\
\hline
\end{array}
$$

Pairs will be Created to check the they are actually following:
1. P1 - P2   ✔️
2. P1 - P3   ✔️
3. P1 - P6   ✔️
4. P2 - P4   ❌
5. P2 - P5   ❌
6. P3 - P4   ✔️
7. P3 - P5   ❌
8. P4 - P6   ✔️
9. P5 - P6   ❌

Probability = 5 / 9  =  55.56 %

In [9]:
y_true = [1,0,0,1,1,0]
y_pred =[0.93 , 0.83 , 0.31 , 0.73 , 0.25 , 0.37]

roc_auc_score(y_true ,y_pred)

np.float64(0.5555555555555556)

In [10]:
#
y_true = [1,0,0,1,1,0]
y_pred = [1,0,0,1,1,0]

roc_auc_score(y_true, y_pred)

np.float64(1.0)

In [11]:
y_true = [1,   0,   0,   1,   1,    0]
y_pred = [0.9, 0.3, 0.4, 0.6, 0.8,  0.7]

roc_auc_score(y_true, y_pred)

np.float64(0.888888888888889)

In [12]:
# when minimum of the '1'(True Values) > maximum of '0'(False Values)
# pair will not get rejected.

# All pairs
# P1 (0.9)
# P1 - N2 → 0.9 > 0.3 ✔️
# P1 - N3 → 0.9 > 0.4 ✔️
# P1 - N6 → 0.9 > 0.5 ✔️
# P4 (0.6)
# P4 - N2 → 0.6 > 0.3 ✔️
# P4 - N3 → 0.6 > 0.4 ✔️
# P4 - N6 → 0.6 > 0.5 ✔️
# P5 (0.8)
# P5 - N2 → 0.8 > 0.3 ✔️
# P5 - N3 → 0.8 > 0.4 ✔️
# P5 - N6 → 0.8 > 0.5 ✔️

# 9/9

y_true = [1,   0,   0,   1,   1,    0]
y_pred = [0.9, 0.3, 0.4, 0.6, 0.8,  0.5]

roc_auc_score(y_true, y_pred)

np.float64(1.0)

# 🔰Nominal Logistic Regression🔰

- Used when we Response is Multi-Categorical

In [13]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='nominal')
df = df.drop('write', axis=1)

x = df.drop('prog', axis=1)
y = df.prog

ses_dummy = pd.get_dummies(x.ses, drop_first=True, prefix='SES').astype(int)
x.drop('ses', axis=1, inplace=True)
x = pd.concat([x,ses_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

x_train = sm.add_constant(x_train, prepend=False)
mod1 = sm.MNLogit(y_train, x_train).fit()
print(mod1.summary())

Optimization terminated successfully.
         Current function value: 0.653667
         Iterations 8
                          MNLogit Regression Results
==============================================================================
Dep. Variable:                   prog   No. Observations:                  160
Model:                        MNLogit   Df Residuals:                      152
Method:                           MLE   Df Model:                            6
Date:                Thu, 18 Jun 2026   Pseudo R-squ.:                  0.3687
Time:                        10:26:07   Log-Likelihood:                -104.59
converged:                       True   LL-Null:                       -165.68
Covariance Type:            nonrobust   LLR p-value:                 5.678e-24
==============================================================================
    prog=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
math           0.0112      0.036      0.312      0.755      -0.059       0.082
SES_2          3.2174      0.685      4.695      0.000       1.874       4.561
SES_3          2.4719      1.121      2.204      0.028       0.274       4.670
const         -1.0727      1.747     -0.614      0.539      -4.496       2.351
------------------------------------------------------------------------------
    prog=3       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
math           0.1181      0.042      2.797      0.005       0.035       0.201
SES_2          5.4410      1.237      4.399      0.000       3.017       7.865
SES_3          6.7918      1.486      4.570      0.000       3.879       9.705
const         -9.3380      2.542     -3.674      0.000     -14.319      -4.357
==============================================================================


*   nulll hypo (Math)  :\
 the math score doen't get influence choice between Program_1 and Program_2

*   nulll hypo (SES_2) :\
whether we belong to SES_1 or SES_2, it does not influence choice between program_1 or program_2.

#

*  every unit increase in maths score,\
as the maths score the probability of choosing SES_2 over SES_1 getting increase.

In [14]:
# nulll hypo (Math)  : the math score doen't get influence choice between Program_1 and Program_2
# nulll hypo (SES_2) : whether we belong to SES_1 or SES_2, it does not influence choice between program_1 or progrsm_2

sudeep = p1 ses1 ----> p2 ses3\
vinnet = p1 ses3 -----> p2 ses3

Sudeep

You wrote:

Sudeep: P1, SES1 → P2, SES3

Interpreting this as:

Currently compare P1 vs P2
SES = 3

For SES3:

Coefficient = -2.4719

Negative coefficient means:

P(P1)
P(P2)
	​


decreases.

So SES3 makes Program 1 more likely than Program 2.

Result

Sudeep → Program 1

#
Vineet

You wrote:

Vineet: P1, SES3 → P2, SES3

Again SES = 3.

Same coefficient:

−2.4719

Negative.

Therefore:

P(P1)>P(P2)
Result

Vineet → Program 1

# 🔰Ordinal Logistic Regression🔰

- multiple categories is in logical order

In [15]:
from statsmodels.miscmodels.ordinal_model import OrderedModel

df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='ordinal')

reg_dummy = pd.get_dummies(df.Region, drop_first=True, prefix='Region').astype(int)
df.drop('Region', axis=1, inplace=True)
df = pd.concat([df,reg_dummy], axis=1)
df.Survival = pd.Categorical(df.Survival, categories=[1,2,3],ordered=True)

x_train, x_test, y_train, y_test = train_test_split(df.drop('Survival',axis=1),df.Survival,test_size=0.2, random_state=20)

mod1=OrderedModel(y_train,x_train,distr='logit').fit(method='bfgs')
print(mod1.summary())

Optimization terminated successfully.
         Current function value: 0.847944
         Iterations: 19
         Function evaluations: 22
         Gradient evaluations: 22
                             OrderedModel Results
==============================================================================
Dep. Variable:               Survival   Log-Likelihood:                -49.181
Model:                   OrderedModel   AIC:                             106.4
Method:            Maximum Likelihood   BIC:                             114.6
Date:                Thu, 18 Jun 2026
Time:                        10:26:07
No. Observations:                  58
Df Residuals:                      54
Df Model:                           2
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ToxicLevel    -0.1255      0.039     -3.196      0.001      -0.203      -0.049
Region_2      -0.6543      0.547     -1.197      0.231      -1.726       0.417
1/2           -7.4417      1.924     -3.867      0.000     -11.213      -3.670
2/3            1.1827      0.158      7.467      0.000       0.872       1.493
==============================================================================

# Count model is used when your response is strictly a whole number

$$
\begin{array}{l}
\text{Whole Numbers} \\
\;\; \vdash \; \text{Less Variation (Under-dispersed)} \rightarrow \text{Poisson} \\
\;\; \vdash \; \text{High Variation (Over-dispersed)} \rightarrow \text{Negative Binomial}
\end{array}
$$

In [16]:
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='poisson')
prog_dummy = pd.get_dummies(df.prog, drop_first=True,prefix='prog').astype(int)
df = df.drop('prog', axis=1)
df = pd.concat([df,prog_dummy], axis=1)
x_train, x_test, y_train, y_test = train_test_split(df.drop('num_awards', axis=1), df['num_awards'], test_size=0.2,random_state=20)
x_train1 = sm.add_constant(x_train, prepend=False)

df_train = pd.concat([x_train1,y_train], axis=1)

mod2 = psn.from_formula("num_awards ~ math+prog_2+prog_3", data=df_train).fit()

Optimization terminated successfully.
         Current function value: 0.871654
         Iterations 6

In [17]:
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='poisson')
prog_dummy = pd.get_dummies(df.prog, drop_first=True,prefix='prog').astype(int)
df = df.drop('prog', axis=1)
df = pd.concat([df,prog_dummy], axis=1)
x_train, x_test, y_train, y_test = train_test_split(df.drop('num_awards', axis=1), df['num_awards'], test_size=0.2,random_state=20)
x_train1 = sm.add_constant(x_train, prepend=False)

df_train = pd.concat([x_train1,y_train], axis=1)

mod2 = psn.from_formula("num_awards ~ math+prog_2+prog_3", data=df_train).fit()

Optimization terminated successfully.
         Current function value: 0.871654
         Iterations 6

In [18]:
mydata = pd.DataFrame([[70,0,0],[70,1,0],[70,0,1]], columns= x_train.columns)

In [19]:
mydata

   math  prog_2  prog_3
0    70       0       0
1    70       1       0
2    70       0       1

In [20]:
mod2.predict(mydata)

0    0.638170
1    1.926336
2    0.920868
dtype: float64

In [21]:
from statsmodels.discrete.discrete_model import NegativeBinomial as ngb
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='neg_bin')
prog_dummy = pd.get_dummies(df['prog'], drop_first=True,prefix='prog').astype(int)
df = df.drop('prog', axis=1)
df = pd.concat([df,prog_dummy], axis=1)
x_train, x_test, y_train, y_test = train_test_split(df.drop('daysabs',axis=1), df['daysabs'], test_size=0.2,random_state=20)
x_train1 = sm.add_constant(x_train)
df_train = pd.concat([x_train1,y_train], axis=1)
model3 = ngb.from_formula("daysabs ~ math+prog_General+prog_Vocational", data=df_train).fit()
model3.summary()

Optimization terminated successfully.
         Current function value: 2.819371
         Iterations: 19
         Function evaluations: 26
         Gradient evaluations: 26

<class 'statsmodels.iolib.summary.Summary'>
"""
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                daysabs   No. Observations:                  251
Model:               NegativeBinomial   Df Residuals:                      247
Method:                           MLE   Df Model:                            3
Date:                Thu, 18 Jun 2026   Pseudo R-squ.:                 0.03229
Time:                        10:26:08   Log-Likelihood:                -707.66
converged:                       True   LL-Null:                       -731.28
Covariance Type:            nonrobust   LLR p-value:                 3.104e-10
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           2.2587      0.144     15.644      0.000       1.976       2.542
math               -0.0070      0.003     -2.506      0.012      -0.012      -0.002
prog_General        0.3942      0.198      1.989      0.047       0.006       0.783
prog_Vocational    -0.7389      0.160     -4.616      0.000      -1.053      -0.425
alpha               0.9326      0.106      8.811      0.000       0.725       1.140
===================================================================================
"""

In [22]:
mydata1 = pd.DataFrame([[60,0,0],[60,1,0],[60,0,1]], columns= x_train.columns)

In [23]:
model3.predict(mydata1)

0    6.285376
1    9.322562
2    3.002024
dtype: float64