<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/PML_R/Day_04_19_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import nltk

import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

from nltk.corpus import stopwords
import re
from collections import Counter


nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
# Sample documents
documents = [
    "I love NLP",
    "NLP is interesting",
    "I love machine learning"
]

# Create BoW model
vectorizer = CountVectorizer() #creates vocabulary


# Convert text into BoW matrix
X = vectorizer.fit_transform(documents)#counts occurances based on vocabulary

# Display as table
df = pd.DataFrame(
    X.toarray(),#sparse matrix to normal
    columns=vectorizer.get_feature_names_out()
)

print(df)

   interesting  is  learning  love  machine  nlp
0            0   0         0     1        0    1
1            1   1         0     0        0    1
2            0   0         1     1        1    0

TF:How often a word appears in a document
IDF:Gives less importance to words appearing in many documents.

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer


# Sample documents
documents = [
    "I love NLP",
    "NLP is interesting",
    "I love machine learning"
]

# Create TF-IDF model
vectorizer = TfidfVectorizer()

# Convert text into TF-IDF matrix
X = vectorizer.fit_transform(documents)

# Display as table
df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

print(df.round(2))

   interesting    is  learning  love  machine   nlp
0         0.00  0.00      0.00  0.71     0.00  0.71
1         0.62  0.62      0.00  0.00     0.00  0.47
2         0.00  0.00      0.62  0.47     0.62  0.00

For Document 0, the most important terms are "love" and "nlp" (TF-IDF = 0.71).

For Document 1, the most important terms are "interesting" and "is" (TF-IDF = 0.62).

For Document 2, the most important terms are "machine" and "learning" (TF-IDF = 0.62).

Words with higher TF-IDF values contribute more to distinguishing one document from the others.

So TF-IDF is often preferred over Bag of Words for text classification and information retrieval.

In [4]:
query = ["machine learning"]

In [5]:
query_vector = vectorizer.transform(query)
print(query_vector.toarray())

[[0.         0.         0.70710678 0.         0.70710678 0.        ]]

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

scores = cosine_similarity(query_vector, X)

print(scores)

[[0.         0.         0.88072413]]

In [10]:
import pandas as pd
import nltk

import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

from nltk.corpus import stopwords
import re
from collections import Counter

import os
os.chdir('/content/drive/MyDrive/CDAC/')


nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [32]:
df=pd.read_csv("spam.csv",encoding="latin1")
df.head()

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [33]:
df=df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1)
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [34]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess(text):

    # lowercase
    text = text.lower()

    # remove special characters except englih characters
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    # tokenize
    words = nltk.word_tokenize(text)

    # remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [35]:
df.iloc[4]

label                                                    ham
message    Nah I don't think he goes to usf, he lives aro...
Name: 4, dtype: object

In [36]:
df['clean']=df['message'].apply(preprocess)

In [37]:
df[25:50]

,label,message,clean
25,ham,Just forced myself to eat a slice. I'm really ...,forced eat slice really hungry tho suck mark g...
26,ham,Lol your always so convincing.,lol always convincing
27,ham,Did you catch the bus ? Are you frying an egg ...,catch bus frying egg make tea eating mom left ...
28,ham,"I'm back &amp; we're packing the car now, I'll...",back amp packing car let know room
29,ham,Ahhh. Work. I vaguely remember that! What does...,ahhh work vaguely remember feel like lol
30,ham,"Wait that's still not all that clear, were you...",wait still clear sure sarcastic x want live u
31,ham,Yeah he got in at 2 and was v apologetic. n ha...,yeah got v apologetic n fallen actin like spoi...
32,ham,K tell me anything about you.,k tell anything
33,ham,For fear of fainting with the of all that hous...,fear fainting housework quick cuppa
34,spam,Thanks for your subscription to Ringtone UK yo...,thanks subscription ringtone uk mobile charged...
35,ham,Yup... Ok i go home look at the timings then i...,yup ok go home look timing msg xuhui going lea...
36,ham,"Oops, I'll let you know when my roommate's done",oops let know roommate done
37,ham,I see the letter B on my car,see letter b car
38,ham,Anything lor... U decide...,anything lor u decide
39,ham,Hello! How's you and how did saturday go? I wa...,hello saturday go texting see decided anything...
40,ham,Pls go ahead with watts. I just wanted to be s...,pls go ahead watt wanted sure great weekend ab...
41,ham,"Did I forget to tell you ? I want you , I need...",forget tell want need crave love sweet arabian...
42,spam,07732584351 - Rodger Burns - MSG = We tried to...,rodger burn msg tried call reply sm free nokia...
43,ham,WHO ARE YOU SEEING?,seeing
44,ham,Great! I hope you like your man well endowed. ...,great hope like man well endowed lt gt inch
45,ham,No calls..messages..missed calls,call message missed call
46,ham,Didn't you get hep b immunisation in nigeria.,get hep b immunisation nigeria
47,ham,"Fair enough, anything going on?",fair enough anything going
48,ham,"Yeah hopefully, if tyler can't do it I could m...",yeah hopefully tyler could maybe ask around bit
49,ham,U don't know how stubborn I am. I didn't even ...,u know stubborn even want go hospital kept tel...

In [38]:
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

In [39]:
df['label'].value_counts()

label
0    4825
1     747
Name: count, dtype: int64

In [40]:
X = df['message']
y = df['label']

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(X)

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [58]:
X_train.shape, X_test.shape

((4457, 8672), (1115, 8672))

In [59]:
y_train.value_counts()

label
0    3859
1     598
Name: count, dtype: int64

In [60]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced',max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [61]:
predictions = model.predict(X_test)

In [62]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [63]:
print("Accuracy:", accuracy_score(y_test, predictions))

print(classification_report(y_test, predictions))

Accuracy: 0.9802690582959641
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       966
           1       0.96      0.89      0.92       149

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [64]:
new_emails = [

     "Hi Chetan, the meeting is scheduled at 10 AM tomorrow.",

    "Claim your prize money immediately."
]

In [65]:
clean_emails = []

for email in new_emails:
    clean_emails.append(preprocess(email))

In [66]:
email_vectors = tfidf.transform(clean_emails)

In [67]:
predictions = model.predict(email_vectors)

In [68]:
predictions

array([0, 1])

In [69]:
for email, pred in zip(new_emails, predictions):

    if pred == 1:
        result = "Spam"
    else:
        result = "Ham"

    print("\nEmail:", email)
    print("Prediction:", result)

Email: Hi Chetan, the meeting is scheduled at 10 AM tomorrow.
Prediction: Ham

Email: Claim your prize money immediately.
Prediction: Spam