<a href="https://colab.research.google.com/github/devdatta1429/BDA_Assignments/blob/main/Stats/Day_13_31_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

from numpy import random
from collections import Counter

from numpy.linalg import inv
from numpy.linalg import eig

import matplotlib
from matplotlib import pyplot as plt

import seaborn as sns

import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from scipy.stats import chisquare
from scipy.stats import chi2_contingency

## 🔰Multiple ANOVA🔰

In [2]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]

In [3]:
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
df.nunique()
df

    Resp  Factor1 Factor2
0     34        1       R
1     43        1       D
2     57        1       R
3     40        1       D
4     85        2       R
5     68        2       D
6     67        2       R
7     53        2       D
8     41        3       R
9     24        3       D
10    42        3       R
11    52        3       D

In [4]:
model = ols('Resp~Factor1+Factor2',df).fit()
res = sm.stats.anova_lm(model)
res

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN

In [6]:
model = ols('Resp~Factor1*Factor2',df).fit()
res = sm.stats.anova_lm(model)
res

# Factor1:Factor2 interactio                                                                                                                                                                                                                        n

                  df       sum_sq     mean_sq         F    PR(>F)
Factor2          1.0   176.333333  176.333333  0.483367  0.506590
Factor1          1.0    28.125000   28.125000  0.077097  0.788312
Factor1:Factor2  1.0     0.125000    0.125000  0.000343  0.985685
Residual         8.0  2918.416667  364.802083       NaN       NaN

## 🔰1-Proportion Test🔰

In [7]:
mu  = 500*0.7

In [8]:
mu

350.0

In [10]:
sd =(500*0.7*0.3)**0.5
sd

10.246950765959598

In [11]:
binom.cdf(370,500,0.7) - binom.cdf(329,500,0.7)

np.float64(0.9547133734363867)

In [13]:
norm.cdf(370.5,mu,sd) - norm.cdf(329.5,mu,sd)

np.float64(0.9545639632657537)

Q. suppose the claim is this batch ha s max 40% students come from maharatstra\
Ho pr <= 0.4\
Ha pr > 0.4

in the smaple of 400 students , 180 stuents are from MH.

- 1-proportion test\
This test is used to compare the proportion calculated from a sample against a claim value and establish whether their difference is statistically significant or not.

In [15]:
160/400

0.4

In [17]:
statsmodels.stats.proportion.proportions_ztest(180,400,0.4, alternative = 'larger')

(np.float64(2.0100756305184238), np.float64(0.022211592425003045))

In [18]:
norm.ppf(2.0100756305184238)

np.float64(nan)

In [19]:
norm.cdf(2.0100756305184238)

np.float64(0.977788407574997)

In [20]:
1 - norm.cdf(2.0100756305184238)

np.float64(0.022211592425003035)


- 2-proportion test\
This test is used to compare the difference of two proportions calculated from two samples against a claim value and establish whether their difference is statistically significant or not

In [23]:
40/70 - 38/80

0.09642857142857142

In [26]:
40/70 - 48/80

-0.02857142857142858

In [27]:
engg = np.array([40,48])

total = np.array([70,80])

statsmodels.stats.proportion.proportions_ztest(engg,total,0.08,alternative='smaller')

(np.float64(-1.3471563869719667), np.float64(0.08896493545619544))

In [30]:
# Claimed pattern for the Qualifications

In [31]:
#Btech - 0.4 , Mtech - 0.1 , MCA - 0.3 , Msc - 0.2
#Btech - 50 , Mtech - 20 , MCA - 45 , Msc - 25

# whether count obtainde from the sample follow the pattern or not.

# ***Chi-Square***

*🔰Chi-Square for goodness fo fit🔰*

In [32]:
counts = np.array([50,20,45,25])
pattern = np.array([0.4 , 0.1 , 0.3 , 0.2])

In [33]:
exp_counts = sum(counts) * pattern

In [34]:
exp_counts

array([56., 14., 42., 28.])

In [35]:
from scipy.stats import chisquare

In [36]:
scipy.stats.chisquare(counts, f_exp=exp_counts)

Power_divergenceResult(statistic=np.float64(3.7500000000000004), pvalue=np.float64(0.2897557811933843))

In [37]:
counts = np.array([70,10,35,45])

In [39]:
exp_counts = sum(counts) * pattern
exp_counts

array([64., 16., 48., 32.])

In [40]:
scipy.stats.chisquare(counts, f_exp=exp_counts)

Power_divergenceResult(statistic=np.float64(11.614583333333334), pvalue=np.float64(0.008827096989130126))

In [41]:
sum((exp_counts - counts)**2/exp_counts)

np.float64(11.614583333333334)

In [42]:
((exp_counts - counts)**2/exp_counts)

array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

*🔰Chi-Square for degree of association🔰*

In [43]:
from scipy.stats import chi2_contingency

In [ ]:
# Three Foods - South,Maharastrian,Gujrati

In [45]:
food = np.array([[45, 70 ,60],[70, 40, 25]])
food

array([[45, 70, 60],
       [70, 40, 25]])

In [46]:
scipy.stats.chi2_contingency(food)

Chi2ContingencyResult(statistic=np.float64(23.25424258416586), pvalue=np.float64(8.920832446902749e-06), dof=2, expected_freq=array([[64.91935484, 62.09677419, 47.98387097],
       [50.08064516, 47.90322581, 37.01612903]]))

In [52]:
np.array([70, 40, 25])

array([70, 40, 25])

In [51]:
np.sum([70, 40, 25])

np.int64(135)

In [55]:
np.mean([70, 40, 25])

np.float64(45.0)

In [56]:
food = np.array([70, 40, 25])-np.mean([70, 40, 25])

In [58]:
food**2

array([625.,  25., 400.])